[workspace.package]
authors = ["Dmitriy Kumshayev"]
description = "FIX parser library"
license = "MIT"
repository = "https://github.com/dkumsh/fixlite"
edition = "2021"
keywords = ["fix", "serialization"]
version = "0.3.4"

[workspace]
resolver = "2"

members = ["fixlite", "fixlite_derive", "fixlite_example"]

[workspace.dependencies]
chrono = "0.4"
thiserror = "1.0"
quote = "1.0.37"
syn = {  version = "2.0.96", features = ["derive", "visit-mut"] }

