[package]
name = "fixlite"
authors.workspace = true
version.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace  = true
readme.workspace  = true
description = "fixlite FIX parser core library"

[dependencies]
chrono = { workspace = true }
fixlite_derive = { version = "0.5.2", path = "../fixlite_derive", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
fixlite_derive = { path = "../fixlite_derive" }

[features]
default = []
derive = ["fixlite_derive"]
checksum = []
