[package]
name = "fixlite"
authors.workspace = true
version.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace  = true
readme.workspace  = true
description = "fixlite FIX parser core library"

[dependencies]
chrono = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
syn = { workspace = true }
thiserror = { workspace = true }
ryu = { workspace = true }

[dev-dependencies]
fixlite_derive = { path = "../fixlite_derive" }
