[package]
name = "fixlite_example"
authors.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
version.workspace = true
publish = false

[dependencies]
chrono =  { workspace = true }
fixlite = { path = "../fixlite" }
fixlite_derive = { path = "../fixlite_derive" }
memchr = "2.7.5"
