[package]
name = "fixlite_example"
authors.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
version.workspace = true
publish = false
readme.workspace  = true
license.workspace = true

[dependencies]
chrono = { workspace = true }
fixlite = { path = "../fixlite" }
fixlite_derive = { path = "../fixlite_derive" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "parser_bench"
harness = false