name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  test-and-dry-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: fmt, clippy & tests
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings
          cargo test

      - name: cargo publish (dry-run workspace)
        run: cargo publish --dry-run --workspace
